const data = {
  products: [
    {
      slug: '1',
      name: 'Naruto',
      category: 'Clothes',
      image: '/images/img1.png',
      price: 1500,
      countInStock: 10,
      brand: 'Naruto',
      rating: 4.5,
      numReviews: 10,
      description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      slug: '2',
      name: 'Naruto',
      category: 'Clothes',
      image: '/images/img2.png',
      price: 1500,
      countInStock: 10,
      brand: 'Naruto',
      rating: 4.5,
      numReviews: 10,
      description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      slug: '3',
      name: 'Naruto',
      category: 'Clothes',
      image: '/images/img3.png',
      price: 1500,
      countInStock: 10,
      brand: 'Naruto',
      rating: 4.5,
      numReviews: 10,
      description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      slug: '4',
      name: 'Naruto',
      category: 'Clothes',
      image: '/images/img4.png',
      price: 1500,
      countInStock: 10,
      brand: 'Naruto',
      rating: 4.5,
      numReviews: 10,
      description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
  ],
};

export default data;
